name: hdfeos

on: [push, pull_request]

jobs:
  build:
    name: Build hdfeos
    runs-on: ubuntu-latest
    steps:
      - name: Install Autotools Dependencies (Linux)
        run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin
      - name: Install HDF4
        run: |
          wget https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.15/src/hdf-4.2.15.tar.gz
          tar zxvf hdf-4.2.15.tar.gz
          cd hdf-4.2.15
          ./configure --prefix=/usr/local --enable-shared --enable-hdf4-xdr -disable-fortran --disable-netcdf
          cat config.log
          make
          make check
          sudo make install
          ls /usr/local/lib
          cd ..
          rm -rf hdf-4.2.15 hdf-4.2.15.tar.gz 
      - name: Install HDF-EOS2
        run: |
          wget -O hdfeos.tar.gz "https://git.earthdata.nasa.gov/projects/DAS/repos/hdfeos/raw/hdf-eos2-3.0-src.tar.gz?at=3128a738021501c821549955f6c78348e5f33850"
          tar zxvf hdfeos.tar.gz
          cd hdf-eos2-3.0
          cat /usr/local/bin/h4cc
          echo $LD_LIBRARY_PATH
          ./configure CC=/usr/local/bin/h4cc LDFLAGS="-L/usr/local/lib" --prefix=/usr/local/ --enable-install-include
          cat config.log
          make
          make check
          sudo make install
