name: hdfeos5

on: [push, pull_request]

jobs:
  build:
    name: Build hdfeos5
    runs-on: ubuntu-latest
    steps:
      - name: Install Autotools Dependencies (Linux)
        run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin
      - name: Install HDF5
        run: |
          wget -O HDF-EOS5.2.0.tar.gz "https://git.earthdata.nasa.gov/projects/DAS/repos/hdfeos5/raw/hdf-eos5-2.0-src.tar.gz?at=refs%2Fheads%2FHDFEOS5_2.0"
          tar zxvf HDF-EOS5.2.0.tar.gz
          cd hdf-eos5-2.0
          ./configure CC=/usr/local/bin/h5cc --prefix=/usr/local/ --enable-install-include        
          wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.22/src/hdf5-1.8.22.tar.gz
          tar zxvf hdf5-1.8.22.tar.gz
          cd hdf5-1.8.22
          ./configure --prefix=/usr/local  --with-default-api-version=v16
          make
          make check
          sudo make install
      - name: Install HDF-EOS5
        run: |
          wget -O HDF-EOS5.2.0.tar.gz "https://git.earthdata.nasa.gov/projects/DAS/repos/hdfeos5/raw/hdf-eos5-2.0-src.tar.gz?at=refs%2Fheads%2FHDFEOS5_2.0"
          tar zxvf HDF-EOS5.2.0.tar.gz
          cd hdf-eos5-2.0
          ./configure CC=/usr/local/bin/h5cc --prefix=/usr/local/ --enable-install-include
          make
          make check
          sudo make install
